// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    'getting-started',
    {
      type: 'category',
      label: 'Face Interface',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'face-interface',
        },
      ],
    },
  ]
};

module.exports = sidebars;
