// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    'getting-started',
    {
      type: 'category',
      label: 'Face Interface',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'face-interface',
        },
      ],
    },
    {
      type: 'category',
      label: 'x40 Vest',
      collapsed: false,
      items: [
        {
          type: 'html',
          value: `
            <a
              class="menu__link"
              tabindex="0"
              href="https://docs.google.com/document/d/1j84h-7OIkRO9KTNtq_mKxri_7PsSNUnL/view"
              target="_blank"
            >
              Guide by ProBendingVR
              <svg width="13.5" height="13.5" aria-hidden="true" viewBox="0 0 24 24" style="margin-left: auto;">
                <path
                  fill="currentColor"
                  d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z"
                ></path>
              </svg>
            </a>
          `,
        },
      ],
    },
  ]
};

module.exports = sidebars;
